import type { Metadata } from "next";
import type { ReactNode } from "react";
import { Inter } from "next/font/google";
import "./globals.css";
import { auth } from "@/lib/auth";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import GlobalLayout from "@/components/global-layout";
import ScrollProvider from "@/context/scroll-provider";
import { ViewTransitions } from "next-view-transitions";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: ReactNode;
}>) {
    const session = await auth();
    return (
        <ViewTransitions>
            <html lang="en" className="scroll-smooth" suppressHydrationWarning>
                <body className={inter.className}>
                    <ScrollProvider>
                        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                            <GlobalLayout session={session}>{children}</GlobalLayout>
                            <Toaster position="top-right" richColors />
                        </ThemeProvider>
                    </ScrollProvider>
                </body>
            </html>
        </ViewTransitions>
    );
}
